import sanitizeHtml from "sanitize-html";

const allowedTags = [
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "blockquote",
  "p",
  "a",
  "ul",
  "ol",
  "nl",
  "li",
  "b",
  "i",
  "strong",
  "em",
  "strike",
  "code",
  "hr",
  "br",
  "div",
  "table",
  "thead",
  "caption",
  "tbody",
  "tr",
  "th",
  "td",
  "pre",
  "iframe",
  "img",
  "svg",
  "main",
  "path",
  "defs",
  "linearGradient",
  "rect",
  "polygon",
  "text",
  "tspan",
  "g",
  "defs",
  "linearGradient",
  "stop"
];

export default function(content) {
  return sanitizeHtml(content, {
    allowedTags: allowedTags,
    disallowedTagsMode: "discard",
    allowedAttributes: {
      a: ["href", "name", "target"],
      img: ["src"],
      svg: ["*"],
      path: ["*"],
      text: ["*"],
      g: ["*"],
      defs: ["*"],
      linearGradient: ["*"],
      tspan: ["*"],
      stop: ["*"]
    },
    selfClosing: [
      "img",
      "br",
      "hr",
      "area",
      "base",
      "basefont",
      "input",
      "link",
      "meta"
    ],
    allowedSchemes: ["http", "https", "ftp", "mailto"],
    allowedSchemesByTag: {},
    allowedSchemesAppliedToAttributes: ["href", "src", "cite"],
    allowProtocolRelative: true
  });
}
